export const SET_PARTICIPANTS = 'SET_PARTICIPANTS';
export const SET_SELECTED_PARTICIPANT = 'SET_SELECTED_PARTICIPANT';
export const SET_SELECTED_PARTICIPANT_ACCOUNTS = 'SET_SELECTED_PARTICIPANT_ACCOUNTS';
export const SET_HISTORY_OPERATIONS = 'SET_HISTORY_OPERATIONS';
export const GET_HISTORY_REQUEST = 'GET_HISTORY_REQUEST';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAILURE = 'GET_HISTORY_FAILURE';
