export const SET_PARTICIPANTS = 'SET_PARTICIPANTS';
export const SET_SELECTED_PARTICIPANT = 'SET_SELECTED_PARTICIPANT';
export const SET_SELECTED_PARTICIPANT_ACCOUNTS = 'SET_SELECTED_PARTICIPANT_ACCOUNTS';
